---
# MongoDB container deployment
- name: Pull MongoDB image
  docker_image:
    name: "{{ docker_username }}/e_health_management:{{ app_version }}"
    source: pull
    force_source: yes

- name: Stop and remove existing MongoDB container
  docker_container:
    name: mongodb
    state: absent
    force_kill: yes
  ignore_errors: true

- name: Start MongoDB container
  docker_container:
    name: mongodb
    image: "{{ docker_username }}/e_health_management:{{ app_version }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ mongodb_port }}:27017"
    volumes:
      - /data/mongodb:/data/db
    networks:
      - name: telemedicine-network
    networks_cli_compatible: yes
