---
# Docker configuration
- name: Ensure Docker network exists
  ignore_errors: true
  docker_network:
    name: telemedicine-network
    state: present

- name: Check Docker login status
  ignore_errors: true
  command: docker info
  register: docker_info
  changed_when: false

- name: Display Docker info
  debug:
    var: docker_info.stdout_lines
  when: docker_info.rc == 0
