apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: e-health
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gupta9939/e_health_management_backend:02
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: e-health-config
              key: MONGO_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: e-health-config
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: e-health-secrets
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: e-health
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort
