apiVersion: v1
kind: ConfigMap
metadata:
  name: telemedicine-config
  namespace: telemedicine
data:
  MONGO_URI: "mongodb://mongodb-service:27017/telemedicine"
  PORT: "5000"
  REACT_APP_API_BASE_URL: "http://backend-service:5000"
