apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: e-health

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - backend.yaml
  - frontend.yaml
