apiVersion: v1
kind: Secret
metadata:
  name: telemedicine-secret
  namespace: telemedicine
type: Opaque
data:
  # Note: These are base64 encoded values
  JWT_SECRET: eW91cl9hY3R1YWxfand0X3NlY3JldA== # base64 encoded "your_actual_jwt_secret"
  # Cloudinary credentials (if still needed)
  # CLOUDINARY_CLOUD_NAME: <base64-encoded-value>
  # CLOUDINARY_API_KEY: <base64-encoded-value>
  # CLOUDINARY_API_SECRET: <base64-encoded-value>
