---
# Common tasks for all servers
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false

- name: Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  changed_when: false
  failed_when: false

- name: Display Docker status
  debug:
    msg: "Docker is {{ 'installed' if docker_check.rc == 0 else 'not installed' }}"

- name: Display Docker Compose status
  debug:
    msg: "Docker Compose is {{ 'installed' if docker_compose_check.rc == 0 else 'not installed' }}"
