---
# Main Ansible playbook for E-Health Management application deployment
- name: Configure E-Health Management Application
  hosts: all
  become: false
  vars:
    docker_username: gupta9939
    app_version: "02"
    mongodb_port: 27017
    backend_port: 5000
    frontend_port: 3000
    mongo_uri: "mongodb://mongodb:27017/telemedicine"
    jwt_secret: "your_jwt_secret_key_here"
    react_app_api_base_url: "http://localhost:5000"

  roles:
    - common
    - docker
    - mongodb
    - backend
    - frontend
